# Generated by Django 3.0.2 on 2020-01-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amb_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=50)),
                ('urltoimage', models.CharField(max_length=50)),
                ('published', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=50)),
            ],
        ),
    ]
